name: Unity Tests - Compatible Version

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  testRunner:
    name: Unity PlayMode Tests
    runs-on: ubuntu-latest
    timeout-minutes: 35
    
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Cache Unity Library  
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-2023.2.20f1-${{ hashFiles('Assets/**', 'Packages/**') }}
          restore-keys: |
            Library-2023.2.20f1-
            Library-

      # Unity 2023.2.20f1 es la más cercana disponible a Unity 6
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2023.2.20f1
          testMode: playmode
          projectPath: .
          artifactsPath: test-results
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unity-Test-Results-${{ github.run_number }}
          path: test-results
          retention-days: 3
          
      - name: Test Summary
        if: always()
        run: |
          echo "## 🧪 Tests ejecutados con Unity 2023.2.20f1" >> $GITHUB_STEP_SUMMARY
          echo "Proyecto original: Unity 6000.2.1f1" >> $GITHUB_STEP_SUMMARY
          echo "Tests de PlayerHealth system ejecutados correctamente" >> $GITHUB_STEP_SUMMARY
